// The capture corpus's report (npm run capture:corpus writes it after the runs):, generated from
// the records of .cache/corpus/records/ — each site's fidelity at every breakpoint (the share of pixels alike over the
// whole page, scaled by the shorter page over the longer: the study's "adjusted" figure), against the target of 98 %
// (DEC-62); which sites count is the rule of tools/capture/score.ts.
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import type { SiteRecord } from './corpus.capture.ts';
import { siteVerdict, TARGET, type SiteVerdict } from './score.ts';
import { WIDTHS } from './fidelity.ts';

const RECORDS = path.join('.cache', 'corpus', 'records');
const sites = (JSON.parse(fs.readFileSync('tools/capture/corpus.json', 'utf8')) as { sites: { id: string }[] }).sites;
const records = sites.flatMap((site) => {
  const file = path.join(RECORDS, `${site.id}.json`);
  if (!fs.existsSync(file)) return [];
  const one = JSON.parse(fs.readFileSync(file, 'utf8')) as SiteRecord;
  const manifest = path.join('.cache', 'corpus', 'references', site.id, 'manifest.json');
  const current = fs.existsSync(manifest) ? createHash('sha256').update(fs.readFileSync(manifest)).digest('hex') : null;
  const fresh = current !== null && one.referenceManifestSha256 === current;
  const record = fresh ? one : { ...one, widths: [], problem: 'Stale or unbound reference; remeasure before using this score' };
  return [{ record, verdict: siteVerdict(record, fresh, WIDTHS) }];
});
const widths = [...new Set(records.flatMap(({ record }) => record.widths.map((w) => w.width)))].sort((a, b) => b - a);
const cell = (record: SiteRecord, width: number) => {
  const one = record.widths.find((w) => w.width === width);
  return one === undefined ? '—' : `${one.pixelMatchAdjusted.toFixed(1)}${one.pixelMatchAdjusted >= TARGET ? '' : ' ✗'}`;
};
const replayCell = (record: SiteRecord, width: number) => {
  const one = record.referenceReplay?.find((entry) => entry.width === width);
  return one === undefined ? '—' : `${one.pixelMatchCommon.toFixed(1)} %`;
};
const stabilityCell = (record: SiteRecord, width: number) => {
  const one = record.referenceStability?.find((entry) => entry.width === width);
  return one === undefined ? '—' : `${one.pixelMatchCommon.toFixed(1)}${one.pixelMatchCommon >= 99 ? '' : ' ✗'} %`;
};
const readinessCell = (record: SiteRecord, width: number) => {
  const one = record.referenceReadiness?.find((entry) => entry.width === width);
  if (one === undefined) return '—';
  const problems = [!one.quiescent ? 'DOM active' : '', one.pendingImages > 0 ? `${one.pendingImages} images pending` : '', one.scrollTruncated ? 'scroll incomplete' : '', !one.networkIdle ? 'network active' : '', one.unseekableVideos > 0 ? `${one.unseekableVideos} videos unseekable` : ''].filter((part) => part !== '');
  return problems.length === 0 ? 'ready' : problems.join('; ');
};
const counted = (kind: SiteVerdict['kind']) => records.filter(({ verdict }) => verdict.kind === kind).length;
const reached = counted('reached');
const verdictCell = (verdict: SiteVerdict) => {
  const at = verdict.widths.map((w) => `${w}px`).join(', ');
  if (verdict.kind === 'reached') return 'at the target';
  if (verdict.kind === 'below') return `below the target at ${at}`;
  if (verdict.kind === 'inconclusive') return `inconclusive: the site varies (${at})`;
  return 'unmeasured';
};
const lines = [
  '# Capture corpus',
  '',
  '<!-- generated by npm run capture:corpus (tools/capture/report.ts) from .cache/corpus/records; never edited by hand -->',
  '',
  `Twenty public sites of the kinds a person captures (\`tools/capture/corpus.json\`), each photographed live at four`,
  'initial viewport widths while its HAR and DOM/runtime snapshot are recorded. The Companion builds from those same',
  'snapshots and HAR resource bytes; the original target is the verified live photograph at that width, never a',
  'degraded HAR replay. A fixed browser clock and seeded Math.random are applied before each navigation. Captures are',
  'imported with File › Import',
  'HTML, exported with File › Export, and compared with the live original at every breakpoint: the share of pixels alike',
  'over the whole page (a channel within 24 of',
  `255), scaled by the shorter page over the longer. Target: ${TARGET} % at every breakpoint (STG-12.6, DEC-62). A site counts`,
  'when its reference is current and every breakpoint reaches the target; what the site blocks or never serves, and a',
  'live page that changes or does not settle, are observations beside the score. A site under the target is',
  `inconclusive when, at every breakpoint under it, its own two live loads also differ by more (live/live under ${TARGET} %).`,
  '',
  `Sites at the target: ${reached} of ${sites.length}. Below the target: ${counted('below')}. Inconclusive (the site varies): ${counted('inconclusive')}. Unmeasured: ${counted('unmeasured')}. Measured: ${records.length}.`,
  '',
  `| Site | Kind | Files | Elements | ${widths.map((w) => `${w}px`).join(' | ')} | Verdict | Observations |`,
  `| --- | --- | --- | --- | ${widths.map(() => '---').join(' | ')} | --- | --- |`,
  ...records.map(({ record: one, verdict }) => `| [${one.id}](${one.url}) | ${one.kind} | ${one.files} | ${one.elements ?? '—'} | ${widths.map((w) => cell(one, w)).join(' | ')} | ${verdictCell(verdict)} | ${one.problem ?? ''} |`),
  '',
  '## Live-load stability',
  '',
  'Two independent live navigations at the same width use the same fixed clock, random seed and initial cookies.',
  'Their unchanged pixel comparison is marked under 99 %; under the target it makes a site under the target inconclusive.',
  '',
  `| Site | ${widths.map((w) => `${w}px live/live`).join(' | ')} |`,
  `| --- | ${widths.map(() => '---').join(' | ')} |`,
  ...records.map(({ record: one }) => `| ${one.id} | ${widths.map((w) => stabilityCell(one, w)).join(' | ')} |`),
  '',
  '## Live-load readiness',
  '',
  'The recorder waits for stable DOM and image requests, then pauses accessible video at its first seekable frame. Incomplete source state is reported separately from export fidelity.',
  '',
  `| Site | ${widths.map((w) => `${w}px readiness`).join(' | ')} |`,
  `| --- | ${widths.map(() => '---').join(' | ')} |`,
  ...records.map(({ record: one }) => `| ${one.id} | ${widths.map((w) => readinessCell(one, w)).join(' | ')} |`),
  '',
  '## Reference replay diagnostic',
  '',
  'The target above is the live photograph taken during recording at each width. This separate comparison shows how',
  'closely a later HAR replay matches that live page; a low value exposes missing resources or changing runtime state.',
  'Replay agreement never replaces the live target or changes the 98 % export threshold.',
  '',
  `| Site | ${widths.map((w) => `${w}px replay`).join(' | ')} |`,
  `| --- | ${widths.map(() => '---').join(' | ')} |`,
  ...records.map(({ record: one }) => `| ${one.id} | ${widths.map((w) => replayCell(one, w)).join(' | ')} |`),
  '',
];
fs.mkdirSync(path.join('.cache', 'logs'), { recursive: true });
fs.writeFileSync(path.join('.cache', 'logs', 'capture-corpus.md'), lines.join('\n'));
console.log(`.cache/logs/capture-corpus.md: ${reached} of ${sites.length} sites at ${TARGET} %, ${records.length} measured`);
