// The motion runtime put together (spec motion-runtime): the factories by name, the start the editor calls on its
// canvas's window, and the same functions written as text for a page — one runtime, never two. Each factory is
// written as its own source, so what a page runs is exactly what the editor's tests run.
import { createEasing } from '../../../core/motion/easing.ts';
import { configText, type RuntimeConfig } from '../../../core/motion/export.ts';
import { createActions } from './actions.ts';
import { createBehaviours } from './behaviours.ts';
import { createLottie } from './lottie.ts';
import { createPlayer } from './player.ts';
import { createScroll } from './scroll.ts';
import { createSplitText } from './split-text.ts';
import { startMotion, type Factories, type MotionController, type StartOptions } from './start.ts';
import { createTargets } from './targets.ts';
import { createTriggers } from './triggers.ts';

export const FACTORIES: Factories = {
  createEasing,
  createTargets,
  createSplitText,
  createActions,
  createLottie,
  createScroll,
  createPlayer,
  createTriggers,
  createBehaviours,
};

// The runtime started on a window (the canvas's iframe, a test's page).
export const startOn = (win: Window, config: RuntimeConfig, options: StartOptions): MotionController => startMotion(win, config, FACTORIES, options);

// The page's motion script (export: js/motion.js; the preview writes it inline): the factories and the start as their
// own source, then the start run on the page with the site's motion data. Plain JavaScript, no library, no module (a
// page opened from file:// runs it too).
export function motionRuntimeSource(config: RuntimeConfig): string {
  const factories = Object.entries(FACTORIES)
    .map(([name, factory]) => `    ${name}: ${(factory as (...args: never[]) => unknown).toString()}`)
    .join(',\n');
  return [
    '// Generated by Builder: the motion of the site (interactions, timelines, behaviours). Plain JavaScript on the Web',
    '// Animations API and the browser\'s scroll timelines; no library.',
    '(function () {',
    "  'use strict';",
    '  var factories = {',
    factories,
    '  };',
    `  (${startMotion.toString()})(window, ${configText(config)}, factories, { mode: 'page' });`,
    '})();',
    '',
  ].join('\n');
}
