import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { FACTORIES, motionRuntimeSource } from './compose.ts';
import { startMotion } from './start.ts';
import { config, fakePage } from './fake-page.ts';

// Every name a module of the runtime or of the core's motion declares at its top level: a factory written into a page
// must name none of them but its own (the page holds no module, only the factories' own sources).
function topLevelNames(): Set<string> {
  const names = new Set<string>();
  const folders = [path.resolve('src/editor/motion/runtime'), path.resolve('src/core/motion')];
  for (const folder of folders) {
    for (const file of fs.readdirSync(folder)) {
      if (!file.endsWith('.ts') || file.endsWith('.test.ts')) continue;
      const text = fs.readFileSync(path.join(folder, file), 'utf8');
      for (const match of text.matchAll(/^(?:export )?(?:const|let|function|class) ([A-Za-z_$][\w$]*)/gm)) names.add(match[1] as string);
    }
  }
  return names;
}

describe('the runtime written into a page', () => {
  it('writes each factory as its own source, naming nothing of another module', () => {
    const declared = topLevelNames();
    for (const [name, factory] of [...Object.entries(FACTORIES), ['startMotion', startMotion] as const]) {
      const source = (factory as (...args: never[]) => unknown).toString();
      // what the code names, its comments and texts left out
      const code = source.replace(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g, '').replace(/'(?:[^'\\\n]|\\.)*'|"(?:[^"\\\n]|\\.)*"/g, "''");
      // a bundler's import of another module, or a name another module declares, would be undefined on the page
      expect(source, name).not.toMatch(/__vite_ssr_import|__vite_ssr_dynamic_import|\brequire\(|\bimport\(/);
      // a name the factory declares itself (a const, a function, a parameter) is its own
      const own = (other: string): boolean => new RegExp(`\\b(const|let|var|function)\\s+${other}\\b|[(,]\\s*${other}\\s*[,):=]|\\b${other}\\s*=>`).test(source);
      const foreign = [...declared].filter((other) => other !== factory.name && other !== name && !own(other) && new RegExp(`(?<![.\\w$'"-])${other}(?![\\w$:])`).test(code));
      expect(foreign, name).toEqual([]);
    }
  });

  it('runs from its text alone on a page: bound, played, undone', () => {
    const page = fakePage('<button id="go">Go</button><p id="panel" hidden>Hi</p>');
    const source = motionRuntimeSource(
      config({
        bindings: [{ selector: '#go', interaction: { trigger: { kind: 'click' }, timeline: 'Open', control: 'toggle' } }],
        timelines: {
          Open: {
            name: 'Open',
            markers: [],
            actions: [
              { id: 'show', target: { kind: 'selector', selector: '#panel' }, start: 0, duration: 0, effect: { kind: 'display', operation: 'show', transition: 'none', mode: 'hidden' } },
              { id: 'mark', target: { kind: 'self' }, start: 0, duration: 0, effect: { kind: 'attribute', name: 'aria-expanded', value: 'true' } },
              { id: 'rise', target: { kind: 'selector', selector: '#panel' }, start: 0, duration: 300, easing: 'spring(1, 170, 26)', effect: { kind: 'animate', tracks: [{ id: 'y', property: 'translate-y', keyframes: [{ id: 'k', time: 0, value: '1em' }] }] } },
            ],
          },
        },
      }),
    );
    // the page's script runs in a scope of its own: the window, and nothing of this module
    new Function('window', source)(page.win);
    const go = page.document.querySelector('#go') as HTMLElement;
    go.dispatchEvent(new (page.win as unknown as { MouseEvent: typeof MouseEvent }).MouseEvent('click'));
    expect((page.document.querySelector('#panel') as HTMLElement).hidden).toBe(false);
    expect(go.getAttribute('aria-expanded')).toBe('true');
    // the spring reached the page as the linear() curve it traces
    expect(page.animations.find((one) => one.keyframes !== null)?.options.easing).toMatch(/^linear\(0, /);
    page.tick(300);
    go.dispatchEvent(new (page.win as unknown as { MouseEvent: typeof MouseEvent }).MouseEvent('click'));
    page.tick(300);
    page.tick(0);
    expect((page.document.querySelector('#panel') as HTMLElement).hidden).toBe(true);
    expect(go.hasAttribute('aria-expanded')).toBe(false);
  });

  it('holds no editor id, no data attribute, and stays one script for the whole site', () => {
    const source = motionRuntimeSource(config({}));
    expect(source).not.toContain('data-node');
    expect(source.startsWith('// Generated by Builder')).toBe(true);
    expect(source).toContain("(window, {\"bindings\":[]");
  });
});
