import fs from 'node:fs';
import { expect, test, type Page } from '../support/test.ts';
import { openEditor } from '../support/editor.ts';
import { control, runDoor, runs, openExplorer } from './door.ts';
import { unzip } from '../../tools/runner/unzip.ts';

const IMPORT = 'project.importHtml#menu-file';
const read = (page: Page) => page.evaluate(() => (window as unknown as { __builderTestPort: { document(): { pages: { id: string; name: string; file: string; tree: unknown }[] } } }).__builderTestPort.document());
test('import offers three destinations and adds a page without changing either client page', runs(IMPORT), async ({ page }) => {
  await openEditor(page);
  const original = JSON.parse(fs.readFileSync('manifest/features/fixtures/aurora.json', 'utf8'));
  original.pages.push({ id: 'client-contact', name: 'Client contact', file: 'contact.html', tree: { id: 'contact-root', name: 'ContactRoot', type: 'page', tag: 'body', attributes: {}, styles: {}, classes: [], text: null, children: [] } });
  const opening = page.waitForEvent('filechooser');
  await runDoor(page, 'project.open#menu-file');
  await (await opening).setFiles({ name: 'client.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(original)) });
  await expect.poll(async () => (await read(page)).pages.length).toBe(2);
  const before = await read(page);
  const choosing = page.waitForEvent('filechooser');
  await runDoor(page, IMPORT);
  await (await choosing).setFiles({ name: 'legacy.html', mimeType: 'text/html', buffer: Buffer.from('<title>Legacy</title><h1>Imported legacy page</h1>') });
  const dialog = page.locator('[data-region="html-import"]');
  await expect(dialog).toBeVisible();
  await expect(dialog.locator('[data-door^="project.importHtml#destination-"]')).toHaveCount(3);
  await expect(dialog.locator('[data-door="project.importHtml#destination-page"]')).toBeFocused();
  expect(await read(page)).toEqual(before);
  await dialog.locator('[data-door="project.importHtml#destination-page"]').click();
  await expect(dialog).toHaveCount(0);
  const after = await read(page);
  expect(after.pages.slice(0, 2)).toEqual(before.pages);
  expect(after.pages).toHaveLength(3);
  expect(after.pages[2]?.file).toBe('legacy.html');
  await expect(page.frameLocator('.frame__page').getByRole('heading', { name: 'Imported legacy page' })).toBeVisible();
  await page.keyboard.press('Control+z');
  await expect.poll(() => read(page)).toEqual(before);
});

test('a folder adds both pages with their nested images, stylesheet and links', runs(IMPORT), async ({ page }) => {
  await openEditor(page);
  const opening = page.waitForEvent('filechooser');
  await runDoor(page, 'project.open#menu-file');
  await (await opening).setFiles('manifest/features/fixtures/client-site.json');
  await expect.poll(async () => (await read(page)).pages.length).toBe(2);
  const before = await read(page);
  const choosing = page.waitForEvent('filechooser');
  await runDoor(page, 'project.importHtml#menu-file-folder');
  await (await choosing).setFiles('manifest/features/fixtures/folders/legacy');
  await page.locator('[data-door="project.importHtml#destination-page"]').click();
  await expect.poll(async () => (await read(page)).pages.length).toBe(4);
  expect((await read(page)).pages.slice(0, 2)).toEqual(before.pages);
  const frame = page.frameLocator('.frame__page');
  await expect(frame.getByRole('heading', { name: 'Folder home' })).toBeVisible();
  expect(await frame.getByRole('heading').evaluate(el => getComputedStyle(el).color)).toBe('rgb(12, 34, 56)');
  await expect.poll(() => frame.locator('img').evaluate(el => (el as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  const about = (await read(page)).pages.find(p => p.file === 'pages/about.html');
  if (!about) throw new Error('The folder About page was not imported');
  await openExplorer(page);
  await runDoor(page, 'pages.switch#explorer-page-row', { args: { page: (about.tree as { id: string }).id } });
  await expect(frame.getByRole('heading', { name: 'Folder about' })).toBeVisible();
  expect(await frame.getByRole('heading').evaluate(el => getComputedStyle(el).color)).toBe('rgb(12, 34, 56)');
  await expect.poll(() => frame.locator('img').evaluate(el => (el as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  const download = page.waitForEvent('download');
  await runDoor(page, 'project.export#toolbar-top-bar-export');
  const files = unzip(fs.readFileSync(await (await download).path()));
  expect(files.get('pages/about.html')?.toString()).toContain('href="../index-2.html"');
  expect(files.get('pages/about.html')?.toString()).toContain('src="../img/coffee.png"');
  expect(files.has('img/coffee.png')).toBe(true);
});

test('inside import keeps existing contents and a refused text target changes nothing', runs(IMPORT), async ({ page }) => {
  await openEditor(page);
  const opening = page.waitForEvent('filechooser');
  await runDoor(page, 'project.open#menu-file');
  await (await opening).setFiles('manifest/features/fixtures/client-site.json');
  await expect.poll(async () => (await read(page)).pages.length).toBe(2);
  await control(page, 'selection.select#layers-row', { args: { target: 'client-title' } }).click();
  const before = await read(page);
  let choosing = page.waitForEvent('filechooser');
  await runDoor(page, IMPORT);
  await (await choosing).setFiles('manifest/features/fixtures/import/legacy.html');
  await page.locator('[data-door="project.importHtml#destination-inside"]').click();
  await expect(page.locator('[data-region="html-import"] [role="alert"]')).toContainText('Choose a container');
  expect(await read(page)).toEqual(before);
  await page.keyboard.press('Escape');
  await control(page, 'selection.select#layers-row', { args: { target: 'home-root' } }).click();
  choosing = page.waitForEvent('filechooser');
  await runDoor(page, IMPORT);
  await (await choosing).setFiles('manifest/features/fixtures/import/legacy.html');
  await page.locator('[data-door="project.importHtml#destination-inside"]').click();
  await expect(page.locator('[data-region="html-import"]')).toHaveCount(0);
  expect((await read(page)).pages).toHaveLength(2);
  const frame = page.frameLocator('.frame__page');
  await expect(frame.getByRole('heading', { name: 'Client home — keep this page' })).toBeVisible();
  await expect(frame.getByRole('heading', { name: 'Imported legacy page' })).toBeVisible();
  await page.keyboard.press('Control+z');
  await expect.poll(() => read(page)).toEqual(before);
});

test('replacement requires confirmation and one undo restores the entire client project', runs(IMPORT), async ({ page }) => {
  await openEditor(page);
  const opening = page.waitForEvent('filechooser');
  await runDoor(page, 'project.open#menu-file');
  await (await opening).setFiles('manifest/features/fixtures/client-site.json');
  await expect.poll(async () => (await read(page)).pages.length).toBe(2);
  const before = await read(page);
  const choosing = page.waitForEvent('filechooser');
  await runDoor(page, IMPORT);
  await (await choosing).setFiles('manifest/features/fixtures/import/legacy.html');
  await page.locator('[data-door="project.importHtml#destination-replace"]').click();
  await expect(page.getByRole('alertdialog')).toContainText('entire project');
  expect(await read(page)).toEqual(before);
  await page.locator('[data-confirmation="cancel"]').click();
  expect(await read(page)).toEqual(before);
  await page.locator('[data-door="project.importHtml#destination-replace"]').click();
  await page.locator('[data-confirmation="confirm"]').click();
  await expect.poll(async () => (await read(page)).pages.length).toBe(1);
  await page.keyboard.press('Control+z');
  await expect.poll(() => read(page)).toEqual(before);
});
