// The feature table: the one map from every feature of the manifest to its registration, in the
// order of manifest/features/. A feature is registered with registerFeature once it is built, and NOT_AVAILABLE_YET
// until then; a missing or an extra entry is a type error. Its doors, and the controls that stand for an item it
// brings (a palette entry), are usable only while it is registered; the census fails
// a registered feature with no scenario, or one of whose scenarios cannot run or fails. Plain data: the runner and the
// census read it in Node.
import { installFeatureTable, registerFeature, type FeatureTable } from '../core/commands/registry.ts';

export const FEATURES = {
  'assistant-chat': registerFeature('assistant-chat'),
  // 23 the Layout Composer, a removable module (src/modules/layout-composer, installed by app/modules.ts)
  'layout-composer': registerFeature('layout-composer'),
  // 01 foundation
  'editor-shell': registerFeature('editor-shell'),
  'canvas-page-iframe': registerFeature('canvas-page-iframe'),
  // 02 structure editing
  'palette-click-insert': registerFeature('palette-click-insert'),
  'select-click': registerFeature('select-click'),
  'layers-tree': registerFeature('layers-tree'),
  'undo-redo': registerFeature('undo-redo'),
  'delete-element': registerFeature('delete-element'),
  'drag-reorder-canvas': registerFeature('drag-reorder-canvas'),
  'drag-drop-inside': registerFeature('drag-drop-inside'),
  'drag-level-keys-escape': registerFeature('drag-level-keys-escape'),
  'palette-drag-insert': registerFeature('palette-drag-insert'),
  'layers-drag': registerFeature('layers-drag'),
  'move-up-down': registerFeature('move-up-down'),
  'wrap-row-column': registerFeature('wrap-row-column'),
  'drag-side-wrap': registerFeature('drag-side-wrap'),
  'context-menu': registerFeature('context-menu'),
  'nest-into-previous': registerFeature('nest-into-previous'),
  'promote-out': registerFeature('promote-out'),
  duplicate: registerFeature('duplicate'),
  'drag-duplicate': registerFeature('drag-duplicate'),
  'drag-autoscroll': registerFeature('drag-autoscroll'),
  'clipboard-copy-paste': registerFeature('clipboard-copy-paste'),
  'keyboard-tree-walk': registerFeature('keyboard-tree-walk'),
  'hand-keyboard-move': registerFeature('hand-keyboard-move'),
  'text-edit-inline': registerFeature('text-edit-inline'),
  'text-inline-formatting': registerFeature('text-inline-formatting'),
  'rename-element': registerFeature('rename-element'),
  'multi-select-click': registerFeature('multi-select-click'),
  'multi-select-actions': registerFeature('multi-select-actions'),
  unwrap: registerFeature('unwrap'),
  'marquee-select': registerFeature('marquee-select'),
  'select-container-children': registerFeature('select-container-children'),
  'lock-element': registerFeature('lock-element'),
  'hide-element': registerFeature('hide-element'),
  // 03 app and persistence
  'app-menu': registerFeature('app-menu'),
  'ui-language': registerFeature('ui-language'),
  'autosave-restore': registerFeature('autosave-restore'),
  'unsaved-work-guard': registerFeature('unsaved-work-guard'),
  'autosave-crash-recovery': registerFeature('autosave-crash-recovery'),
  'new-blank-page': registerFeature('new-blank-page'),
  'autosave-corruption-recovery': registerFeature('autosave-corruption-recovery'),
  'multi-tab-guard': registerFeature('multi-tab-guard'),
  'project-save-json': registerFeature('project-save-json'),
  'project-open-json': registerFeature('project-open-json'),
  // 04 inspector
  'inspector-panel': registerFeature('inspector-panel'),
  'inspector-number-fields': registerFeature('inspector-number-fields'),
  'props-display': registerFeature('props-display'),
  'props-flex-container': registerFeature('props-flex-container'),
  'props-grid-container': registerFeature('props-grid-container'),
  'props-layout-item': registerFeature('props-layout-item'),
  'props-spacing': registerFeature('props-spacing'),
  'props-size-overflow': registerFeature('props-size-overflow'),
  'props-position': registerFeature('props-position'),
  'color-picker': registerFeature('color-picker'),
  'color-picker-oklch': registerFeature('color-picker-oklch'),
  'color-swatches-eyedropper': registerFeature('color-swatches-eyedropper'),
  'props-typography': registerFeature('props-typography'),
  'props-typography-advanced': registerFeature('props-typography-advanced'),
  'props-background': registerFeature('props-background'),
  'gradient-editor': registerFeature('gradient-editor'),
  'props-border-outline': registerFeature('props-border-outline'),
  'props-effects-basic': registerFeature('props-effects-basic'),
  'shadow-editor': registerFeature('shadow-editor'),
  'props-filters-clip': registerFeature('props-filters-clip'),
  'props-transforms': registerFeature('props-transforms'),
  'props-transition': registerFeature('props-transition'),
  'props-more': registerFeature('props-more'),
  'props-attributes': registerFeature('props-attributes'),
  'inspector-provenance-reset': registerFeature('inspector-provenance-reset'),
  'inspector-property-search': registerFeature('inspector-property-search'),
  'inspector-advanced-mode': registerFeature('inspector-advanced-mode'),
  'inspector-add-property': registerFeature('inspector-add-property'),
  'semantic-tag-switch': registerFeature('semantic-tag-switch'),
  'quick-panel': registerFeature('quick-panel'),
  'multi-select-edit': registerFeature('multi-select-edit'),
  // 05 canvas handles
  'resize-handles': registerFeature('resize-handles'),
  'spacing-handles': registerFeature('spacing-handles'),
  'radius-border-gap-handles': registerFeature('radius-border-gap-handles'),
  'shadow-handles': registerFeature('shadow-handles'),
  // 06 page and export
  'page-properties': registerFeature('page-properties'),
  'base-style': registerFeature('base-style'),
  'export-zip': registerFeature('export-zip'),
  'css-variables-tokens': registerFeature('css-variables-tokens'),
  'export-bem-css': registerFeature('export-bem-css'),
  // 07 elements
  'elements-structure': registerFeature('elements-structure'),
  'elements-text': registerFeature('elements-text'),
  'elements-lists': registerFeature('elements-lists'),
  'nesting-grammar': registerFeature('nesting-grammar'),
  'nesting-grammar-structure': registerFeature('nesting-grammar-structure'),
  'elements-tables': registerFeature('elements-tables'),
  'table-commands': registerFeature('table-commands'),
  'elements-form-structure': registerFeature('elements-form-structure'),
  'element-attributes-aria': registerFeature('element-attributes-aria'),
  'shared-style-classes': registerFeature('shared-style-classes'),
  'elements-form-inputs': registerFeature('elements-form-inputs'),
  'elements-form-inputs-rules': registerFeature('elements-form-inputs-rules'),
  'forms-masks-validation': registerFeature('forms-masks-validation'),
  'elements-form-controls': registerFeature('elements-form-controls'),
  'elements-media-images': registerFeature('elements-media-images'),
  'elements-media-embeds': registerFeature('elements-media-embeds'),
  'elements-svg-shapes': registerFeature('elements-svg-shapes'),
  'elements-interactive': registerFeature('elements-interactive'),
  'natural-child-command': registerFeature('natural-child-command'),
  'props-element-specific': registerFeature('props-element-specific'),
  'settings-class-management': registerFeature('settings-class-management'),
  'settings-audit': registerFeature('settings-audit'),
  // 08 templates and components
  'templates-layout': registerFeature('templates-layout'),
  'templates-content': registerFeature('templates-content'),
  'templates-sections': registerFeature('templates-sections'),
  'reusable-components': registerFeature('reusable-components'),
  'repeat-element': registerFeature('repeat-element'),
  'templates-components': registerFeature('templates-components'),
  // 09 panels
  'palette-search-groups': registerFeature('palette-search-groups'),
  'palette-density': registerFeature('palette-density'),
  'layers-expand-collapse-all': registerFeature('layers-expand-collapse-all'),
  'layers-search': registerFeature('layers-search'),
  'layers-row-columns': registerFeature('layers-row-columns'),
  'layers-row-colours': registerFeature('layers-row-colours'),
  // 10 view and positioning
  'zoom-keyboard-buttons': registerFeature('zoom-keyboard-buttons'),
  'rotation-handle': registerFeature('rotation-handle'),
  'zoom-wheel-pan': registerFeature('zoom-wheel-pan'),
  rulers: registerFeature('rulers'),
  'guides-manual': registerFeature('guides-manual'),
  'canvas-outlines-zones': registerFeature('canvas-outlines-zones'),
  'layout-grid-overlay': registerFeature('layout-grid-overlay'),
  'workspace-settings-dialog': registerFeature('workspace-settings-dialog'),
  'absolute-free-drag': registerFeature('absolute-free-drag'),
  'absolute-nudge': registerFeature('absolute-nudge'),
  'absolute-anchors': registerFeature('absolute-anchors'),
  'align-distribute': registerFeature('align-distribute'),
  'snap-toggle-settings': registerFeature('snap-toggle-settings'),
  'snap-while-moving': registerFeature('snap-while-moving'),
  'smart-guides': registerFeature('smart-guides'),
  'hover-measure': registerFeature('hover-measure'),
  // 11 responsive and states
  'breakpoints-switch': registerFeature('breakpoints-switch'),
  'breakpoint-overrides': registerFeature('breakpoint-overrides'),
  'state-styles': registerFeature('state-styles'),
  // 12 preview, embed, theme
  'preview-mode': registerFeature('preview-mode'),
  'embed-html': registerFeature('embed-html'),
  'theme-switch': registerFeature('theme-switch'),
  // 13 workspace
  'dock-toggles': registerFeature('dock-toggles'),
  'command-bar': registerFeature('command-bar'),
  'command-bar-set-property': registerFeature('command-bar-set-property'),
  'shortcuts-panel': registerFeature('shortcuts-panel'),
  'workbench-panel': registerFeature('workbench-panel'),
  'panel-resize': registerFeature('panel-resize'),
  'floating-panels': registerFeature('floating-panels'),
  'panel-combine-tabs': registerFeature('panel-combine-tabs'),
  'workspace-persist-reset': registerFeature('workspace-persist-reset'),
  'status-bar': registerFeature('status-bar'),
  // 14 accessibility and keyboard
  'accessibility-checks': registerFeature('accessibility-checks'),
  'layers-keyboard-navigation': registerFeature('layers-keyboard-navigation'),
  'keyboard-panel-navigation': registerFeature('keyboard-panel-navigation'),
  // 15 clipboard and styles
  'clipboard-cut-system': registerFeature('clipboard-cut-system'),
  'copy-paste-styles': registerFeature('copy-paste-styles'),
  // 16 HTML import
  'html-import-structure': registerFeature('html-import-structure'),
  'html-import-cleaning': registerFeature('html-import-cleaning'),
  'html-import-styles': registerFeature('html-import-styles'),
  'html-import-media-queries': registerFeature('html-import-media-queries'),
  'html-import-states': registerFeature('html-import-states'),
  'html-import-roundtrip': registerFeature('html-import-roundtrip'),
  'clipboard-paste-external': registerFeature('clipboard-paste-external'),
  // 17 code panel
  'code-panel-view': registerFeature('code-panel-view'),
  'code-panel-selection-sync': registerFeature('code-panel-selection-sync'),
  'code-panel-copy-download': registerFeature('code-panel-copy-download'),
  'code-panel-edit-css': registerFeature('code-panel-edit-css'),
  'code-panel-edit-html': registerFeature('code-panel-edit-html'),
  // 18 animation and events
  'timeline-animations': registerFeature('timeline-animations'),
  'timeline-keyframes': registerFeature('timeline-keyframes'),
  'timeline-animation-settings': registerFeature('timeline-animation-settings'),
  'timeline-preview': registerFeature('timeline-preview'),
  'export-keyframes': registerFeature('export-keyframes'),
  'events-actions': registerFeature('events-actions'),
  'export-events-js': registerFeature('export-events-js'),
  // 23 motion (plan stage 10)
  'motion-interactions': registerFeature('motion-interactions'),
  'motion-timeline': registerFeature('motion-timeline'),
  'motion-keyframes': registerFeature('motion-keyframes'),
  'motion-preview': registerFeature('motion-preview'),
  'motion-behaviours': registerFeature('motion-behaviours'),
  'export-motion-js': registerFeature('export-motion-js'),
  // 19 pages, files, assets
  'explorer-pages': registerFeature('explorer-pages'),
  'explorer-file-system': registerFeature('explorer-file-system'),
  'link-picker': registerFeature('link-picker'),
  'explorer-assets': registerFeature('explorer-assets'),
  'explorer-assets-use': registerFeature('explorer-assets-use'),
  'export-assets': registerFeature('export-assets'),
  'export-multi-page': registerFeature('export-multi-page'),
  'export-file-tree': registerFeature('export-file-tree'),
  'page-seo-meta': registerFeature('page-seo-meta'),
  'custom-fonts': registerFeature('custom-fonts'),
  'explorer-open-folder': registerFeature('explorer-open-folder'),
  'code-panel-edit-js': registerFeature('code-panel-edit-js'),
  // 20 shortcut sweep
  'shortcuts-e2e-sweep': registerFeature('shortcuts-e2e-sweep'),
  // 21 layout and structure
  'layout-actions': registerFeature('layout-actions'),
  'canvas-grid-editor': registerFeature('canvas-grid-editor'),
  // 23 content and data
  'data-collections': registerFeature('data-collections'),
  'data-import': registerFeature('data-import'),
  'data-binding': registerFeature('data-binding'),
  'data-pages': registerFeature('data-pages'),
  'shared-regions': registerFeature('shared-regions'),
  'project-breakpoints': registerFeature('project-breakpoints'),
  'side-by-side-view': registerFeature('side-by-side-view'),
  'value-presets': registerFeature('value-presets'),
  'project-language': registerFeature('project-language'),
  'batch-rename': registerFeature('batch-rename'),
  'command-bar-find': registerFeature('command-bar-find'),
  'site-colours': registerFeature('site-colours'),
  'class-moves': registerFeature('class-moves'),
  'style-suggestions': registerFeature('style-suggestions'),
  'component-master-edit': registerFeature('component-master-edit'),
  'component-variants': registerFeature('component-variants'),
  'capture-url': registerFeature('capture-url'),
} as const satisfies FeatureTable;

installFeatureTable(FEATURES);

// the table's reader (core/commands/registry.ts), for the tools and tests that load the table to read it
export { isFeatureBuilt } from '../core/commands/registry.ts';
