// The texts of the behaviour map (manifest/generated/behavior.json and behavior.md), the same for the generator
// (tools/map/generate.ts) and for the detector that compares them with the files on disk
// (tools/runner/model/machine.test.ts): keys in a fixed order, no date, no absolute path. Two machines: the gesture
// machine's table, run from the code, and the modes of interaction with what each refuses while it is on
// (src/editor/input/modes.ts, the investigation's C6).
import { MODES, REFUSED_WHILE, type Mode } from '../../src/editor/input/modes.ts';
import { gestureTable, IGNORED_ON_PURPOSE, ignoredOf, mermaidOf } from './gesture-table.ts';

export function behaviorFiles(): { readonly json: string; readonly markdown: string } {
  const gesture = gestureTable();
  const ignored = ignoredOf(gesture.transitions).map((combination) => ({ combination, why: IGNORED_ON_PURPOSE[combination] ?? null }));
  const refused = Object.entries(REFUSED_WHILE) as [Mode, readonly Mode[]][];
  const modes = { source: 'src/editor/input/modes.ts', modes: MODES, refusedWhile: Object.fromEntries(refused) };
  const json = `${JSON.stringify({ machines: { gesture: { source: 'src/editor/input/pointer/machine.ts', threshold: gesture.threshold, transitions: gesture.transitions, ignored }, modes } }, null, 2)}\n`;
  const markdown = [
    '# Behaviour map (generated by tools/map/generate.ts; do not edit)',
    '',
    '## The gesture machine (src/editor/input/pointer/machine.ts)',
    '',
    '```mermaid',
    mermaidOf(gesture.transitions),
    '```',
    '',
    'Ignored on purpose:',
    '',
    ...ignored.map((i) => `- ${i.combination}: ${i.why ?? 'NO REASON DECLARED'}`),
    '',
    '## The modes of interaction (src/editor/input/modes.ts)',
    '',
    `Modes: ${MODES.join(', ')}.`,
    '',
    '| While | Never opens |',
    '|---|---|',
    ...refused.map(([held, never]) => `| ${held} | ${never.join(', ')} |`),
    '',
  ].join('\n');
  return { json, markdown };
}
