// The texts of the behaviour map (manifest/generated/behavior.json and behavior.md), the same for the generator
// (tools/map/generate.ts) and for the detector that compares them with the files on disk
// (tools/runner/model/machine.test.ts): keys in a fixed order, no date, no absolute path.
import { gestureTable, IGNORED_ON_PURPOSE, ignoredOf, mermaidOf } from './gesture-table.ts';

export function behaviorFiles(): { readonly json: string; readonly markdown: string } {
  const gesture = gestureTable();
  const ignored = ignoredOf(gesture.transitions).map((combination) => ({ combination, why: IGNORED_ON_PURPOSE[combination] ?? null }));
  const json = `${JSON.stringify({ machines: { gesture: { source: 'src/editor/input/pointer/machine.ts', threshold: gesture.threshold, transitions: gesture.transitions, ignored } } }, null, 2)}\n`;
  const markdown = [
    '# Behaviour map (generated by tools/map/generate.ts; do not edit)',
    '',
    '## The gesture machine (src/editor/input/pointer/machine.ts)',
    '',
    '```mermaid',
    mermaidOf(gesture.transitions),
    '```',
    '',
    'Ignored on purpose:',
    '',
    ...ignored.map((i) => `- ${i.combination}: ${i.why ?? 'NO REASON DECLARED'}`),
    '',
  ].join('\n');
  return { json, markdown };
}
